// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_local_variable



import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


class Hello {
  Hello._(this._bc, this._bcOffset);
  factory Hello(List<int> bytes) {
    fb.BufferContext rootRef = new fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Hello> reader = const _HelloReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String get message => const fb.StringReader().vTableGet(_bc, _bcOffset, 4, null);
  String get name => const fb.StringReader().vTableGet(_bc, _bcOffset, 6, null);
  int get count => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'Hello{message: $message, name: $name, count: $count}';
  }
}

class _HelloReader extends fb.TableReader<Hello> {
  const _HelloReader();

  @override
  Hello createObject(fb.BufferContext bc, int offset) => 
    new Hello._(bc, offset);
}

class HelloBuilder {
  HelloBuilder(this.fbBuilder) {
    assert(fbBuilder != null);
  }

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable();
  }

  int addMessageOffset(int offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addNameOffset(int offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addCount(int count) {
    fbBuilder.addInt32(2, count);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class HelloObjectBuilder extends fb.ObjectBuilder {
  final String _message;
  final String _name;
  final int _count;

  HelloObjectBuilder({
    String message,
    String name,
    int count,
  })
      : _message = message,
        _name = name,
        _count = count;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(
    fb.Builder fbBuilder) {
    assert(fbBuilder != null);
    final int messageOffset = fbBuilder.writeString(_message);
    final int nameOffset = fbBuilder.writeString(_name);

    fbBuilder.startTable();
    if (messageOffset != null) {
      fbBuilder.addOffset(0, messageOffset);
    }
    if (nameOffset != null) {
      fbBuilder.addOffset(1, nameOffset);
    }
    fbBuilder.addInt32(2, _count);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String fileIdentifier]) {
    fb.Builder fbBuilder = new fb.Builder();
    int offset = finish(fbBuilder);
    return fbBuilder.finish(offset, fileIdentifier);
  }
}
